# Requires the following variables to be added to a .env file
# MYSQL_HOST=db2
# MYSQL_DATABASE=emoncms
# MYSQL_USER=emoncms
# MYSQL_PASSWORD=YOUR_SECURE_PASSWORD
# MYSQL_RANDOM_ROOT_PASSWORD=yes
#
#
#
version: '2'
services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      # - .:/var/www/html
      - emon-phpfiwa:/var/lib/phpfiwa
      - emon-phpfina:/var/lib/phpfina
      - emon-phptimeseries:/var/lib/phptimeseries
    links:
      - db
    env_file:
      - '.env'
  db:
    image: mysql:5.5
    ports: 
      - 3306:3306
    env_file:
      - '.env'
    environment:
      - "MYSQL_HOST=localhost"
    volumes:
      - emon-db-data:/var/lib/mysql/data
volumes:
  emon-phpfiwa:
    driver: local
  emon-phpfina:
    driver: local
  emon-db-data:
    driver: local
  emon-phptimeseries:
    driver: local